### PR TITLE
Keep "R Syntax in result" setting in JASP file

### LINKED ISSUE #3846: [Bug]: "show R-Syntax" not remembered after re-opening file
### JASP Version

0.95.4
Flatpak

### Bug Description

I choose "show R syntax" via settings or via the "results" button in the output
I close the file
I reopen the file
The R-Syntax is not shown. 

### Expected Behaviour

the setting should be remembered.

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/jasp-issues/issues/3846

When creating a new JASP file, the R syntax in results will be displayed according to the user setting in Preferences/Results. This setting is then loaded in the JASP file.
It can be changed in the 'Show R Syntax' in the main menu of the results.
When loading a JASP file, "Show R Syntax in Result" setting of the JASP file is used.
If the user changes its own setting in Preferences/Results, it overwrites the setting of the JASP file.

### CODE REVIEW

File: CommonData/dataset.h [hunk 1]
```diff
@@ -109,7 +111,8 @@ class DataSet : public DataSetBaseNode
 	std::string					_dataFilePath,
 								_databaseJson;
 	
-	bool						_dataFileSynch			= false;
+	bool						_dataFileSynch			= false,
+								_showRSyntax			= false;
```
Comment (JorisGoosen) [inline CommonData/dataset.h:115]: Wouldn't you initialize this to `PreferencesModel::prefs()->showRSyntaxInResults()` somewhere?

As in, I dont see where it gets  initialized?

**Review by JorisGoosen — APPROVED** [review]
setDefaultWorkspaceValues
