### PR TITLE
Reliability bug fixes

### LINKED ISSUE #841: Reliability - Options grayed out inconsistently
* JASP version: 0.13
* OS name and version: macOS Catalina 10.15.5
* Analysis: Reliability
* Bug description: Options are grayed out inconsistently
* Expected behaviour: Options are always grayed out when the statistic they belong to is not selected

#### Steps to reproduce:
1. Open debug data set.
2. In the Reliability module, drag the variables contcor1, contcor2 and contOutlier into the Variables box.
3. In 'Single Test Reliability' > 'Scale Statistics', uncheck McDonald's ω and check Cronbach's α.
4. In 'Individual Item Statistics', 'McDonald's ω (if item dropped)' is grayed out, but in 'Advanced Options', the options concerning McDonald's ω are not grayed out.
5. In 'Advanced Options' > 'McDonald's ω Estimation', check PFA. JASP starts calculating.
6. JASP starts calculating although McDonald's ω was not requested. Nothing changes in the output.

Similarly:
3. In 'Single Test Reliability' > 'Scale Statistics', check McDonald's ω and uncheck Cronbach's α.
4. In 'Individual Item Statistics', 'Cronbach's α (if item dropped)' is grayed out, but in 'Advanced Options', the options concerning Cronbach's α are not grayed out.
5. In 'Advanced Options' > 'Cronbach's α Estimation', check Standardized.
6. JASP starts calculating although Cronbach's α was not requested. Nothing changes in the output.

I think follow-up options should be grayed out consistently if the statistic they belong to is not used in an analysis. Just like the user cannot check 'McDonald's ω (if item dropped) unless s/he has checked 'McDonald's ω' in the first place. That prevents JASP from making unnecessary calculations.

### LINKED ISSUE #853: Reliability analysis does not work for 30 and more items
* JASP version: 0.13

* OS name and version: Windows 10 Pro 64 bit
* Analysis: Single-test Reliability analysis
* Bug description: When I add more than 30 items to reliabiity analysis (I have 36), I get the following error: Error: $ operator is invalid for atomic vectors
* Expected behaviour: analyze all 36 items 

#### Steps to reproduce:
1. Go to 'single test reliability analysis"
2. Add at least 30 items (all ordinal, values range from 1 to 5, no NAs)
3. See error

[data.xlsx](https://github.com/jasp-stats/jasp-issues/files/4880180/data.xlsx)

### LINKED ISSUE #855: Error in Reliability
Originally posted by @antboxg in https://github.com/jasp-stats/jasp-issues/issues/853#issuecomment-654371108

Hi, I have errors too (other data, in v0.12 is OK):

or 

JASP 013, Win 10Pro 64bit

### PR DESCRIPTION
**Pull request by juliuspfadt**
fixes https://github.com/jasp-stats/jasp-issues/issues/841
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/969
fixes https://github.com/jasp-stats/jasp-issues/issues/853
fixes https://github.com/jasp-stats/jasp-issues/issues/855

### CODE REVIEW

**Comment by juliuspfadt** [comment]
Once someone (@JorisGoosen) updates the `Bayesrel` package to 0.6.5.3 (the latest commit), this issues should be fixed with this PR.

File: JASP-Engine/JASP/R/reliabilityAnalysisBayesian.R [hunk 1]
```diff
@@ -416,22 +416,22 @@ reliabilityBayesian <- function(jaspResults, dataset, options) {
   for (i in idxSelected) {
     if (estimators[i] %in% coefficients) {
       if (estimators[i] == "Item-rest correlation") { # no item deleted for item rest cor
-        itemTable$addColumnInfo(name = paste0("postMean", i), title = "Posterior Mean", type = "number", 
+        itemTable$addColumnInfo(name = paste0("postMean", i), title = gettext("Posterior Mean"), type = "number", 
                                 overtitle = gettext("Item-rest correlation"))
-        itemTable$addColumnInfo(name = paste0("lower", i), title = paste0("Lower ", cred, "%"), type = "number", 
+        itemTable$addColumnInfo(name = paste0("lower", i), title = gettextf("Lower %s %%", cred), type = "number",
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisBayesian.R]:
```suggestion
        itemTable$addColumnInfo(name = paste0("lower", i), title = gettextf("Lower %s%% CI", cred), type = "number", 
```

This is only a minor suggestion, as we are not entirely consistent with this in JASP anyway. However, I would at least delete the space between `cred` and the percentage sign (e.g., to display `95%` and not `95 %`)

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R [hunk 2]
```diff
@@ -1,5 +1,7 @@
 reliabilityFrequentist <- function(jaspResults, dataset, options) {
 
+  sink("~/Downloads/log_freq.txt")
+  on.exit(sink(NULL))
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R]: What is this doing here? Should this go away?

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R [hunk 3]
```diff
@@ -144,29 +146,27 @@ reliabilityFrequentist <- function(jaspResults, dataset, options) {
                                          missing = missing, callback = progressbarTick))
           
           relyFit$freq$est$freq_alpha <- Bayesrel:::applyalpha(model[["dat_cov"]])
-          p <- ncol(dataset)
-          Ctmp <- array(0, c(p, p - 1, p - 1))
-          for (i in 1:p){
-            Ctmp[i, , ] <- model[["dat_cov"]][-i, -i]
-          }
+          relyFit[["freq"]][["est"]] <- relyFit[["freq"]][["est"]][c(5, 1, 2, 3, 4)]
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:147]: Is it possible to somehow avoid the  statement `[c(5, 1, 2, 3, 4)]`? What is it doing? Can you perhaps reorder based on names on the elements? Asking just because this way is prone to errors if the output of the package changes (adds or deletes some elements)...

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R [hunk 4]
```diff
@@ -144,29 +146,27 @@ reliabilityFrequentist <- function(jaspResults, dataset, options) {
...
             cors <- array(0, c(options[["noSamples"]], p, p))
             for (i in 1:options[["noSamples"]]) {
               cors[i, , ] <- .cov2cor.callback(relyFit$freq$covsamp[i, , ], progressbarTick)
             }
             relyFit$freq$boot$alpha <- apply(cors, 1, Bayesrel:::applyalpha)
-            if (omegaAna && is.null(relyFit[["freq"]][["omega.error"]])) {
+            if (length(relyFit[["freq"]][["boot"]]) == 4)
               relyFit[["freq"]][["boot"]] <- relyFit[["freq"]][["boot"]][c(4, 1, 2, 3)]
-            } else {
+            else if (length(relyFit[["freq"]][["boot"]]) == 5)
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:163]: This is related to the above, is it possible to somehow avoid these magic numbers?

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R [hunk 5]
```diff
@@ -364,13 +363,14 @@ reliabilityFrequentist <- function(jaspResults, dataset, options) {
   
   cfi <- vector("list", length(boot))
   names(cfi) <- names(boot)
-  
   for (nm in names(boot)) {
-    if (any(is.na(boot[[nm]]))) {
+    if (nm == "mean" | nm == "sd")
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R]:
```suggestion
    if (nm %in% c("mean, "sd"))
```

Either this, or use `||`

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R [hunk 6]
```diff
@@ -364,13 +363,14 @@ reliabilityFrequentist <- function(jaspResults, dataset, options) {
...
       cfi[[nm]] <- c(NA_real_, NA_real_)
-    } else {
-      cfi[[nm]] <- quantile(boot[[nm]], prob = c((1-cfiValue)/2, 1-(1-cfiValue)/2))
-    }
+    else if (all(is.na(boot[[nm]])))
+      cfi[[nm]] <- c(NaN, NaN)
+    else 
+      cfi[[nm]] <- quantile(boot[[nm]], prob = c((1-cfiValue)/2, 1-(1-cfiValue)/2), na.rm = T)
```
Comment (Kucharssim) [inline JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R]:
```suggestion
      cfi[[nm]] <- quantile(boot[[nm]], prob = c((1-cfiValue)/2, 1-(1-cfiValue)/2), na.rm = TRUE)
```

By convention

**Review by Kucharssim — CHANGES_REQUESTED** [review]
I left a couple of minor suggestions, but the code looks good.

I have not been able yet to verify that the linked issues are indeed solved as I have not build JASP in the new Qt so far. I'll do that tomorrow.

**Comment by JorisGoosen** [comment]
Ill make sure BayesRel is updated today.

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R (hunk 3 above)
Comment (juliuspfadt) [reply JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:147]: Ja, I know this looks bad. The problem is that the order of output from the R-package is different from the order of the coefficients in the module. I would like to change this in the future, but for this PR, I won't. I hope that is okay.

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R (hunk 4 above)
Comment (juliuspfadt) [reply JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:163]: I will try to smoothen this out in the future. Would you like me tho get rid of the brackets here? I thought that you leave brackets when the if statement is more than one line?

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R (hunk 3 above)
Comment (Kucharssim) [reply JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:147]: Sure, as a temporary quick fix it's okay.

File: JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R (hunk 4 above)
Comment (Kucharssim) [reply JASP-Engine/JASP/R/reliabilityAnalysisFrequentist.R:163]: No, I think this is fine as it is

**Review by Kucharssim — APPROVED** [review]
Looks good now. 

I just have a point which is not necessary to address in this PR. The main table:

Screenshot 2020-07-10 at 14 17 19

confused me at first, because I implicitly expected it to be organised differently. I believe that in JASP, the standard would be to put different statistics on different rows, and then point estimates and CIs in columns (i.e., the table would be 'transposed' compared to what I see here). Maybe something to think about for future polishing.

**Comment by juliuspfadt** [comment]
> confused me at first, because I implicitly expected it to be organised differently. I believe that in JASP, the standard would be to put different statistics on different rows, and then point estimates and CIs in columns (i.e., the table would be 'transposed' compared to what I see here). Maybe something to think about for future polishing.

Funny you say that. It was organised differently, exactly as you suggested. But it was suggested to me to make the item table and scale table consistent. Since the item table can only have the coefficients as columns and the items in rows (with many items the table would otherwise become too wide), I had to change the scale table to make it more consistent. But I agree with you that a layout with coefficients as rows is nicer.
