### PR TITLE
Make js/html interface translatable

### LINKED ISSUE #1474: [Bug]: Untranslatable string "Click here to add text"
### JASP Version

0.15

### Commit ID

_No response_

### JASP Module

_No response_

### What analysis are you seeing the problem on?

Any analysis, the bug is in jaspDesktop

### What OS are you seeing the problem on?

Ubuntu

### Bug Description

When adding a Note to analysis results, there is a hard-coded English string that cannot yet be translated.

In current development branch, the string is at https://github.com/jasp-stats/jasp-desktop/blob/development/Desktop/html/js/jaspwidgets.js#L375:

```
this.ghostTextDefault = 'Click here to add text';
```

### Expected Behaviour

The string should be translatable.

### Steps to Reproduce

1. Switch to any language other than English.
2. In any analysis result, click on *Add Note*.

### Log (if any)

_No response_

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by shun2wang**
Fix https://github.com/jasp-stats/jasp-issues/issues/1474

Inspired by joris' comment [here](https://github.com/jasp-stats/jasp-issues/issues/1474#issuecomment-957304957), reused the `qsTr() ` to translate the string, I don't know if it's messy, but it works.😜

a test case [here ](https://github.com/shun2wang/jasp-desktop/commit/4b74ebe75ecc44b3b122e8fa7c76f461738df2d6) you can patch the `.qm` files and have a look in jaspNote "Bold" option.

### CODE REVIEW

**Review by JorisGoosen — APPROVED** [review]

**Comment by JorisGoosen** [comment]
Awesome

File: Desktop/html/js/jaspwidgets.js [hunk 1]
```diff
@@ -1,5 +1,26 @@
...
+        i18nStrs = i18nObject
+        return i18nStrs
+}
+
+// Use i18n(...) to call strings to be translated then update them in MainPage.qml
+function i18n(str) {
+	if (typeof str === "string" && str instanceof String) {
+		console.log("i18n can only be used for literal strings")
+	} else {
+		let findI18nStr = i18nStrs[str] !== null && i18nStrs[str] !== undefined;
```
Comment (boutinb) [inline Desktop/html/js/jaspwidgets.js]: Why don't you use the hasOwnProperty method? 
I'm not sure, but I'm afraid by testing ` i18nStrs[str] !== null` this will insert automatically an entry in the object if the key does not exist.

**Review by boutinb — CHANGES_REQUESTED** [review]
Really good initiative. Just a small comment.

File: Desktop/html/js/jaspwidgets.js (hunk 1 above)
Comment (shun2wang) [reply Desktop/html/js/jaspwidgets.js]: yes you are right, that should be more robust.

Comment (shun2wang) [reply Desktop/html/js/jaspwidgets.js]: But this still cannot avoid returning `null `and `undefined`, because this is still valid for undefined.

We can be optimistic though, since the strings to be translated are created by the programmer and not the user, so I intend to return a value in any error case and just report the error in the console, anyway future reviewers of the PR should notice

**Review by boutinb — APPROVED** [review]
