### PR TITLE
wait longer before opening file from arguments

### LINKED ISSUE #1920: [Bug]: Troubles opening large .jasp files on Mac
### JASP Version

0.16.4

### Commit ID

_No response_

### JASP Module

JAGS

### What analysis are you seeing the problem on?

JAGS analysis

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

For one .jasp file I consistently have troubles opening it by just double clicking on the file.
I believe this is because the .jasp file is too big (186 MB)
Screenshot 2022-11-29 at 15 28 12

I have other .jasp files from the same module that open just fine, but that are all less than 10MB. 

I will attached a .jasp file "that works" (SignalDetectionTheory_RecognitionMemory) and the .jasp file I have troubles with (ThurstoneScaling_RankingUSStates), maybe you are able to reproduce the bug.

[SignalDetectionTheory_RecognitionMemory.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/10113974/SignalDetectionTheory_RecognitionMemory.jasp.zip)

I cannot upload the ThurstoneScaling .jasp file, but this is the OSF page where I stored it:
https://osf.io/38rjz

### Expected Behaviour

The .jasp file should open when I click on it, even if it is a large file.

### Steps to Reproduce

1. Double-click on the file (doesn't work)
2. Open JASP first, then under Open --> Computer select the .jasp file
3. This should open the analysis

### Log (if any)

_No response_

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by JorisGoosen**
Fixes https://github.com/jasp-stats/jasp-issues/issues/1920 Troubles opening large .jasp files on Mac

Now we wait for both loading the resultspage and the ribbon/dynamicmodules

### CODE REVIEW

File: Desktop/mainwindow.cpp [hunk 1]
```diff
@@ -544,6 +544,8 @@ void MainWindow::loadQML()
 		ActiveModules::getActiveCommonModules(),
 		ActiveModules::getActiveExtraModules());
 	
+	emit qmlLoaded();
```
Comment (boutinb) [inline Desktop/mainwindow.cpp]: This is not a signal

**Review by boutinb — APPROVED** [review]

File: Desktop/mainwindow.cpp (hunk 1 above)
Comment (JorisGoosen) [inline Desktop/mainwindow.cpp]:
```suggestion
	qmlLoaded();
```
