### PR TITLE
synchronizing now works without crashing again

### LINKED ISSUE #3436: [Crash]: JASP crashes when I try to sync data from csv file
### System Info

-------- Application Info --------
JASP Version: JASP 0.19.3 (Apple Silicon)
Build Branch: 0.19.3
Build Date: Jan  3 2025 12:51:39 (Netherlands)
Last Commit: c8710df5442149527b0692cc1367ea5b3c982d04

-------- Basic Info --------
Operating System: macOS Sonoma (14.5)
Product Version: 14.5
Kernel Type: darwin
Kernel Version: 23.5.0
Architecture: arm64
Install Path: /Applications/JASP.app/Contents/MacOS
Platfotm Name: cocoa
System Local: en_US

### JASP Module

Unrelated

### Is there a specific analysis that caused the crash?

_No response_

### Log files

[JASP 2025-05-09 16_05_55 Desktop.log](https://github.com/user-attachments/files/20128338/JASP.2025-05-09.16_05_55.Desktop.log)

[JASP 2025-05-09 16_05_55 Engine 0.log](https://github.com/user-attachments/files/20128340/JASP.2025-05-09.16_05_55.Engine.0.log)

### Steps to Reproduce

1. Open saved JASP file
2. Open csv file in Excel, edit csv file, save file, close file
3. Select Sync data in JASP, browse and find file, select file
4. JASP starts to say "Synchronize Data" with loading bar, which goes half way across
5. JASP closes

This happens on both my Mac and PC, and it happens with many different files. I updated JASP on my Mac and it didn't fix the problem.

### PR DESCRIPTION
**Pull request by JorisGoosen**
fixes https://github.com/jasp-stats/jasp-issues/issues/3436

### CODE REVIEW

File: CommonData/databaseinterface.cpp [hunk 1]
```diff
@@ -2041,15 +2042,20 @@ void DatabaseInterface::_runStatementsRepeatedly(const std::string & statements,
...
 	const auto id = std::this_thread::get_id();
 
 	if(_dbCreated && _dbCreator == id)
 		return _dbCreated;
 	
-	if(_dbs.count(id))
-		return _dbs.at(id);
-	
-	load();
+	if(!_dbs.count(id))
```
Comment (boutinb) [inline CommonData/databaseinterface.cpp:2052]: I think this is not thread-safe, and you should lock the mutex before the test.

**Review by boutinb — APPROVED** [review]
It works fine now.
I have just one comment about the use of a mutex

File: CommonData/databaseinterface.cpp (hunk 1 above)
Comment (JorisGoosen) [reply CommonData/databaseinterface.cpp:2052]: https://stackoverflow.com/questions/14127379/does-const-mean-thread-safe-in-c11 and count is const
