### PR TITLE
Fix for the prior posterior plot incorrectly switching the bf10 and bf01 label

### LINKED ISSUE #796: Summary Statistics Bayesian Independent Samples T-Test: Labels in prior and posterior plots switch upon changing from BF10 to BF01, while they shouldn't
* JASP version: 0.12.1

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

### PR DESCRIPTION
**Pull request by JTPetter**
Fixes jasp-stats/jasp-issues#796

https://github.com/jasp-stats/jaspSummaryStatistics/pull/3

### CODE REVIEW

File: JASP-Engine/JASP/R/commonsummarystatsttestbayesian.R [hunk 1]
```diff
@@ -361,7 +361,7 @@
     n2                        = 0 ,
     paired                    = FALSE,
     BF10user                  = BFlist[["BF10"]],
-    yAxisLegendRobustnessPlot = BFPlots,
+    yAxisLegendRobustnessPlot = bfPlotsH1H0,
```
Comment (akashrajkn) [inline JASP-Engine/JASP/R/commonsummarystatsttestbayesian.R]: This causes the unit tests to fail. (The robustness plot expects a string. Can you make the necessary change?)

**Review by akashrajkn — CHANGES_REQUESTED** [review]

**Review by akashrajkn — APPROVED** [review]

**Comment by AlexanderLyNL** [comment]
@JTPetter could you please also make this PR to the module?
