### PR TITLE
Several formatting fixes and or tweaks

### LINKED ISSUE #3693: [Bug]: Tukey post-hoc comparison result shows “,00” instead of “1,00” in JASP 0.95.1
### JASP Version

0.95.1

### Commit ID

_No response_

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

_No response_

### What OS are you seeing the problem on?

Windows 11

### Bug Description

In version 0.95.1, when running a Tukey post-hoc test, some results in the output table display incorrectly as “,00” instead of “1,00”.

- This happens when the expected value should be “1.00”.

- The leading digit before the comma/decimal point is missing.

- In earlier versions of JASP (for example, 0.19.3), this formatting issue did not occur — the leading digit was displayed correctly.

Results in JASP 0.19.3 (previous version)

Values were displayed correctly with the leading digit:

Image

Results in JASP 0.95.1 (current version)

Some results incorrectly omit the leading digit:

Image

Here is the JASP file I am using:

[base de datos 3.zip](https://github.com/user-attachments/files/22365334/base.de.datos.3.zip)

### Expected Behaviour

Expected Behaviour

The results should display “1,00” instead of “,00” when the value is one.

More generally, it would be useful to have an option to always show the leading digit before the comma/decimal point, even if it is zero.

Example: show “0,05” instead of “,05”, or “1,00” instead of “,00”.

This feature would improve clarity, avoid misinterpretation, and keep consistency with earlier versions (e.g., 0.19.3).

### Steps to Reproduce

Steps to reproduce:

1. Open JASP 0.95.1

2. Perform an ANOVA followed by a Tukey post-hoc comparison among groups

3. Check the result table for comparisons where the mean difference is 1.00

4. Observe that the table shows “,00” instead of “1,00”

### Log (if any)

_No response_

### More Debug Information

-------- Application Info --------
JASP Version: JASP 0.95.1
Build Branch: development
Build Date: Aug 20 2025 13:37:25 (Netherlands)
Last Commit: 180d14c18d13c107ee7c16b0993ff7e1cc02680b

-------- Basic Info --------
Operating System: Windows 11 Version 24H2
Product Version: 11
Kernel Type: winnt
Kernel Version: 10.0.26100
Architecture: x86_64
Install Path: C:/Program Files/WindowsApps/45842JASP.JASP_0.95.11.0_x64__wz6q9dg667qsj
Platfotm Name: windows
System Local: es_PY

-------- Extra Info --------
Current code page
P�gina de c�digos activa: 850
P�gina de c�digos activa: 65001

Nombre de host:                            DESKTOP-8D003PB
Nombre del sistema operativo:              Microsoft Windows 11 Home Single Language
Versión del sistema operativo:             10.0.26100 N/D Compilación 26100
Fabricante del sistema operativo:          Microsoft Corporation
Configuración del sistema operativo:       Estación de trabajo independiente
Tipo de compilación del sistema operativo: Multiprocessor Free
Propietario registrado:                    user
Organización registrada:                   
Id. del producto:                          00342-43428-50330-AAOEM
Fecha de instalación original:             20/6/2025, 16:46:01
Tiempo de arranque del sistema:            13/9/2025, 16:31:08
Fabricante del sistema:                    LENOVO
Modelo del sistema:                        82C7
Tipo de sistema:                           x64-based PC
Procesadores:                              1 Procesadores instalados.
                                           [01]: AMD64 Family 23 Model 24 Stepping 1 AuthenticAMD ~2100 Mhz
Versión del BIOS:                          LENOVO E8CN34WW, 28/4/2022
Directorio de Windows:                     C:\Windows
Directorio de sistema:                     C:\Windows\system32
Dispositivo de arranque:                   \Device\HarddiskVolume1
Configuración regional del sistema:        es-mx;Español (México)
Idioma de entrada:                         es-mx;Español (México)
Zona horaria:                              (UTC-03:00) Asunción
Memoria física total:                      10.116 MB
Memoria física disponible:                 1.884 MB
Memoria virtual: tamaño máximo:            14.763 MB
Memoria virtual: disponible:               1.146 MB
Memoria virtual: en uso:                   13.617 MB
Ubicaciones de archivos de página:         C:\pagefile.sys
Dominio:                                   WORKGROUP
Servidor de inicio de sesión:              \\DESKTOP-8D003PB
Revisiones:                                3 revisión(es) instaladas.
                                           [01]: KB5064401
                                           [02]: KB5060829
                                           [03]: KB5062862
Tarjetas de red:                           2 Tarjetas de interfaz de red instaladas.
                                           [01]: Bluetooth Device (Personal Area Network)
                                                 Nombre de conexión: Conexión de red Bluetooth 2
                                                 Estado:             Medios desconectados
                                           [02]: Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
                                                 Nombre de conexión: Wi-Fi 2
                                                 DHCP habilitado:    Sí
                                                 Servidor DHCP:      192.168.100.1
                                                 Direcciones IP
                                                 [01]: 192.168.100.107
                                                 [02]: fe80::5a03:4bea:183a:4349
Seguridad basada en virtualización:        Estado: No habilitado
                                           App Control for Business policy: Forzado
                                           App Control for Business user mode policy: Desactivado
                                           Características de seguridad habilitadas:
Requisitos Hyper-V:                        Extensiones de modo de monitor de VM: Sí
                                           Se habilitó la virtualización en el firmware: Sí
                                           Traducción de direcciones de segundo nivel: Sí
                                           La prevención de ejecución de datos está disponible: Sí

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by JorisGoosen**
Disables thousands separators in most results-formats. For currencies it can still be enabled through the interface prefs. Ive also added a format `thousands` that will enable it for any numberformat. Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2869

Also disables that thousands separatores interface pref by default.

Also makes sure that p-values that are rounded to 1.0 dont lose their 1 Fixes https://github.com/jasp-stats/jasp-issues/issues/3693

@RensDofferhoff I think we can still push this to development and make any evt hotfix from there.

### CODE REVIEW

File: Desktop/html/js/utils.js [hunk 1]
```diff
@@ -20,60 +21,60 @@ function formatFixed(value, fixIt)
...
+		useGrouping: useThousandsSeparators || thousands
 	});
 	
 	return amount == "." ? amount : formatter.format(amount)
 }
 
-function formatFixed(number, digitsFrac, noZeroLead=false) {
+function handleNoZeroLead(number, result, noZeroLead)
+{
+	if(number >= 0 && number < 1 && noZeroLead && !result.startsWith("1")) //we need to check whether it starts with despite number < 1 because of rounding in the formatting
```
Comment (JorisGoosen) [inline Desktop/html/js/utils.js]:
```suggestion
	if(number >= 0 && number < 1 && noZeroLead && !result.startsWith("1")) //we need to check whether it starts with 1 despite number < 1 because of rounding in the formatting
```
