### PR TITLE
Bugfixes networkanalysis

### LINKED ISSUE #641: New version 12 chops off variable names in Network analysis
* JASP version: 0.12
 Windows 10
* OS name and version:
* Analysis: Network analysis cuts off variable names
* Bug description: When I set "Show variable names in legend" the new version cuts off the variable names
* Expected behaviour: Variable names are complete, this worked in prior versions.

image

Network analysis consumer energy incentives Figure 3

[18 24 college or degree.xlsx](https://github.com/jasp-stats/jasp-issues/files/4339617/18.24.college.or.degree.xlsx)

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/698
Fixes https://github.com/jasp-stats/jasp-issues/issues/641

Network plots that include a legend are now automatically 1.4 times larger than plots that do not include a legend. The number 1.4 is handpicked by me, other suggestions are welcome.

### CODE REVIEW

File: JASP-Engine/JASP/R/networkanalysis.R [hunk 1]
```diff
@@ -728,8 +729,12 @@ NetworkAnalysis <- function(jaspResults, dataset, options) {
 
   names(allLegends) <- names(allNetworks) # allows indexing by name
 
+  basePlotSize <- 320
+  legendMultiplier <- 0.4 * basePlotSize
```
Comment (TimKDJ) [inline JASP-Engine/JASP/R/networkanalysis.R]: 1.4 or 0.4?

Comment (TimKDJ) [reply JASP-Engine/JASP/R/networkanalysis.R]: Nvm this results in the same thing.

Comment (vandenman) [reply JASP-Engine/JASP/R/networkanalysis.R]: x + 0.4 * x = 1.4 * x

**Comment by TimKDJ** [comment]
If I add a grouping variable I get this error:

[groupingVarErrorNetwork.zip](https://github.com/jasp-stats/jasp-desktop/files/4359583/groupingVarErrorNetwork.zip)

(just rename)

**Comment by vandenman** [comment]
good catch, I thought too easy about the problem.

**Comment by TimKDJ** [comment]
All issues seem fixed so that's nice! I do wonder if we want to make the size of the network plots uniform when you have a grouping factor (not sure if that's all that do-able, as one of them will be more narrow I guess):

network_diff_sizes

Edit: Maybe the legend should be separate if there are multiple plots?

**Comment by vandenman** [comment]
Okay so I looked at it some more and changed it to this:

image

Apparently, `qgraph` has an argument that controls the legend to plot ratio called `GLratio` and if there is a legend the plot is set to `width * (1 + 1 / GLratio)`. The default is 2.5.

This option is now available to users, I think it's a pretty good quality of life change to deal with jasp-stats/jasp-issues#641

**Comment by TimKDJ** [comment]
Nice, this works well. Could you update the English/Dutch documentation?

**Review by TimKDJ — APPROVED** [review]
