### PR TITLE
- Make sure the keys for labels are stored as string

### LINKED ISSUE #1337: JASP quit unexpectedly after trying to open .sav
* JASP version: 0.14.1.0 

* OS name and version: macOS 11.4 (20F71)
* Bug description: When I try to open a .sav file (e.g, https://www.europeansocialsurvey.org/data/ ) JASP quit unexpectedly (see attached file for further detail).
* Expected behaviour: To open the file. 

[report.zip](https://github.com/jasp-stats/jasp-issues/files/6646197/report.zip)

### PR DESCRIPTION
**Pull request by JorisGoosen**
instead of dangerous readstat_value_t/s... Apparently those values get wiped somehow somewhere on some systems.

- Fixes https://github.com/jasp-stats/jasp-issues/issues/1337 (Crash on sav load)
- Also added a bunch of commented out logstatements

### CODE REVIEW

File: Desktop/data/importers/readstatimporter.cpp [hunk 1]
```diff
@@ -113,6 +108,14 @@ ImportDataSet* ReadStatImporter::loadFile(const std::string &locator, boost::fun
...
 	data->buildDictionary(); //Not necessary for opening this file but synching will break otherwise...
 
+
+	Log::log() << "Freeing readstat structs" << std::endl;
+	readstat_parser_free(parser);
+
+#ifdef WIN32
+	io_cleanup();
+#endif
+
```
Comment (boutinb) [inline Desktop/data/importers/readstatimporter.cpp:118]: Did you check if this change (freeing stuff after setting the labels) fixes the issue?

**Review by boutinb — COMMENTED** [review]
I don't see why changing the key by a string should solve this issue...
Are you sure that moving the code to free the parser after making the labels is not enough to solve this issue?

**Review by boutinb — APPROVED** [review]

File: Desktop/data/importers/readstatimporter.cpp (hunk 1 above)
Comment (JorisGoosen) [reply Desktop/data/importers/readstatimporter.cpp:118]: Of course
