### PR TITLE
Filter settings should be removed after closing the workspace

### LINKED ISSUE #2344: [Bug] filter still active after reopen new session
### JASP Version

0.18.1

### Commit ID

_No response_

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Filtering data

### What OS are you seeing the problem on?

Windows 11

### Bug Description

In a csv data set >600 observations from 21 different student teams, I filter out team 18. Then close JASP to do some external editing on the data. Reopening the cleaned and dataset in a fresh JASP instance, the filter still is active, with no way to clear it?!

### Expected Behaviour

Filters should have been cleared upon reopening a data set.

### Steps to Reproduce

1.
2.
3.
...

### Log (if any)

_No response_

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

### PR DESCRIPTION
**Pull request by boutinb**
Fixes https://github.com/jasp-stats/jasp-issues/issues/2344

2 issues:

- the labelFilterGenerator keeps a copy of the R constructed filter string: this is unnecessary, it can use directly this string from the Filter object
- the _columnNameUsedInEasyFilter map in DataSetPackage must be cleared when it is reset.
-

### CODE REVIEW

File: Desktop/data/labelfiltergenerator.cpp [hunk 1]
```diff
@@ -18,13 +18,15 @@ std::string labelFilterGenerator::generateFilter()
...
 	std::stringstream newGeneratedFilter;
+	Filter* filter = DataSetPackage::pkg()->filter();
+	std::string filterRScript = filter ? filter->constructorR() : "";
 
 	newGeneratedFilter << "generatedFilter <- ";
 
 	if(neededFilters == 0)
 	{
-		if(easyFilterConstructorRScript == "")	return DEFAULT_FILTER_GEN;
-		else									newGeneratedFilter << "("<< easyFilterConstructorRScript <<")";
```
Comment (JorisGoosen) [inline Desktop/data/labelfiltergenerator.cpp:27]: ❤️

**Review by JorisGoosen — APPROVED** [review]
